language: csharp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    mono: none
    dotnet: 1.0.0-preview2-003121
    env: DOTNETCORE=1
deploy:
  provider: script
  skip_cleanup: true
#  script:
#    - cd NTwitch && nuget push *.nupkg $NUGET_KEY -verbosity detailed
branches:
  only:
  - master
  - dev
script:
  - dotnet restore
  - dotnet build ./Aux/NTwitch --configuration Release --version-suffix $TRAVIS_BRANCH$TRAVIS_BUILDNUMBER