language: csharp
solution: NTwitch.sln
git:
  depth: 1
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    mono: none
    dotnet: 1.0.0-preview2-003131
    env: DOTNETCORE=1
    
script:
  - bash build.sh

deploy:
  skip_cleanup: true
  provider: script
  script:
    - bash deploy.sh