language: csharp
solution: NTwitch.sln
git:
  depth: 1
branches:
  only:
  - master
  - dev
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    mono: none
    dotnet: 1.0.0-preview2-003131
    env: DOTNETCORE=1
script:
  - sudo apt-get install dotnet-dev-1.0.1
  - dotnet restore
  - dotnet build --configuration Release --version-suffix beta-$TRAVIS_BUILDNUMBER

#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#    - cd NTwitch && nuget push *.nupkg $NUGET_KEY -verbosity detailed
