language: csharp
solution: NTwitch.sln
git:
  depth: 1
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    mono: none
    dotnet: 1.0.0-preview2-003131
    env: DOTNETCORE=1
    
script:
  - sudo apt-get install dotnet-dev-1.0.1
  - dotnet restore
  - dotnet build --configuration Release --version-suffix beta-$TRAVIS_BUILDNUMBER

deploy:
  provider: script
  skip_cleanup: true
  script:
    - dotnet pack "src/NTwitch/NTwitch.csproj" -c "Release" -o "../../nuget" --no-build 
    - dotnet pack "src/NTwitch.Core/NTwitch.Core.csproj" -c "Release" -o "../../nuget" --no-build 
    - dotnet pack "src/NTwitch.Rest/NTwitch.Rest.csproj" -c "Release" -o "../../nuget" --no-build 
    - dotnet nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
  on:
    branch: master
