language: csharp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-003121
    env: DOTNETCORE=1

deploy:
  provider: script
  skip_cleanup: true
  script:
    - xbuild /p:Configuration=Release NTwitch.sln
#    - cd NTwitch && nuget push *.nupkg $NUGET_KEY -verbosity detailed

branches:
  only:
  - master
  - dev