# configuration for "master" branch
# build in Release mode and deploy to NuGet
-
  branches:
    only:
      - master

  version: '0.0.0.1'
  configuration: Release
  before_build: 
    - dotnet restore
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
  deploy:
    provider: NuGet
    api_key:
      secure: $Env:NUGET_KEY
    artifact: /.*\.symbols\.nupkg/
  artifacts:
    - path: '**\*.nupkg'

# configuration for "dev" branch
# build in Release mode and deploy to NuGet pre-release
-
  branches:
    only:
      - dev

  version: '0.0.1-beta{build}'
  before_build: 
    - dotnet restore
    - ps: $Env:DOTNET_BUILD_VERSION = "beta$Env:APPVEYOR_BUILD_NUMBER"
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
  deploy:
    provider: NuGet
    api_key:
      secure: $Env:NUGET_KEY
    artifact: /.*\.symbols\.nupkg/
  artifacts:
    - path: '**\*.nupkg'

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug