version: 0.0.5branches:
  only:
  - master
  - dev
skip_tags: true
image: Visual Studio 2017 RC
configuration: Release
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}-beta-{build}'
  assembly_file_version: '{version}-beta-{build}'
  assembly_informational_version: '{version}-beta-{build}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal