# configuration for "master" branch
# build in Release mode and deploy to NuGet
-
  branches:
    only:
      - master

  version: '0.0.1'
  configuration: Release
  deploy:
    provider: NuGet

# configuration for "dev" branch
# build in Release mode and deploy to NuGet pre-release
-
  branches:
    only:
      - dev

  version: '0.0.1-beta{build}'
  configuration: Release
  deploy:
    provider: NuGet

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug